export const REQUEST_HIT_DICE = 'REQUEST_HIT_DICE'
export const SET_HIT_DICE = 'SET_HIT_DICE'
export const SET_HIT_DICE_LOOKUP = 'SET_HIT_DICE_LOOKUP'
export const REQUEST_HIT_DICE_COMPLETE = 'REQUEST_HIT_DICE_COMPLETE'
