export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_CATEGORIES_LOOKUP = 'SET_CATEGORIES_LOOKUP'
export const REQUEST_CATEGORIES_COMPLETE = 'REQUEST_CATEGORIES_COMPLETE'
