export const REQUEST_MONSTER_LIST = 'REQUEST_MONSTER_LIST'
export const SET_MONSTER_LIST = 'SET_MONSTER_LIST'
export const SELECT_MONSTER = 'SELECT_MONSTER'
export const SET_SELECTED_MONSTER = 'SET_SELECTED_MONSTER'
